server.port: 27060

spring:
  application.name: mallApp
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true
      discovery:
        enabled: true
        instanceId: mallApp_0
        serviceName: mallApp
        hostname: localhost
        port: ${server.port}
        healthCheckUrl: http://${spring.cloud.consul.discovery.hostname}:${server.port}/actuator/health
        healthCheckInterval: 10s
        tags: dev

  sleuth:
    traceId128: true
    sampler.probability: 1.0
  zipkin.base-url: http://localhost:9411

logging:
  level.org.springframework.web: DEBUG
  # Adds trace and span IDs to logs (when a trace is in progress)
  pattern.level: '[%X{X-B3-TraceId}/%X{X-B3-SpanId}]%-5p [%t] %C{2} - %m%n'
